## 1
name: Instrument Tests

## Actions that will be executed when you push code currently none
on:
  push:

  android_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Grant execute permission for script
        run: chmod +x ./scripts/setup_env.sh

      - shell: bash
        env:
          TELNYX_SIP_USER: ${{ secrets.TELNYX_SIP_USER }}
          TELNYX_SIP_PASSWORD: ${{ secrets.TELNYX_SIP_PASSWORD }}
          TELNYX_SIP_TOKEN: ${{ secrets.TELNYX_SIP_TOKEN }}
        run:  |
          sh ./scripts/setup_env.sh -u "$TELNYX_SIP_USER" -p "$TELNYX_SIP_PASSWORD" -t "$TELNYX_SIP_TOKEN"

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest
