name: Scheduled Unit Tests

on:
  schedule:
    - cron:  '*/30 5,17 * * *'

jobs:
  # 1 Run unit tests
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Grant execute permission for script
          run: chmod +x ./scripts/update_properties.sh

      - name: Print Login Params Values
        run: |
          bash update_properties.sh ${{ secrets.TELNYX_SIP_USER }} ${{ secrets.TELNYX_SIP_PASSWORD }}

      - name: Assemble app debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Unit tests
        run: ./gradlew test