
## 1
name: Unit test on Push

## Actions that will be executed when you push code currently none
on:
  push:

## 2
jobs:
  # 3 Unit Test Script
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Update Username from Secrets
        env:
          MOCK_USERNAME: {{ secrets.TELNYX_SIP_USER }}
          run: echo MOCK_USERNAME="$MOCK_USERNAME" > ./local.properties

      - name: Update Password from Secrets
        env:
          MOCK_USERNAME: ${{ secrets.TELNYX_SIP_PASSWORD }}
          run: echo MOCK_PASSWORD="$MOCK_PASSWORD" > ./local.properties

      - name: Assemble app debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Unit tests
        run: ./gradlew test